### ISSUE TITLE
Problem running the example to get planet parameters

### ISSUE THREAD

**Issue by JVSeidel** [ucl-exoplanets/pylightcurve#2]
Hello!

I have been trying to run this nifty piece of code on my Mac. It installed without issues, but now I'm trying to run one of the examples and it breaks...

Here is the code I'm trying to run (copy&paste of one of the examples in your Readme): 

import pylightcurve as plc
import matplotlib.pyplot as plt
import numpy as np

(planet, stellar_logg, stellar_temperature, stellar_metallicity, rp_over_rs, fp_over_fs,
period, sma_over_rs, eccentricity, inclination, periastron, mid_time) = plc.find_oec_parameters('hd209458b')

print (planet, stellar_logg, stellar_temperature, stellar_metallicity, rp_over_rs, fp_over_fs,
period, sma_over_rs, eccentricity, inclination, periastron, mid_time)

I checked that the package was installed correctly and I definitely have a good internet connection, however still this happens:

Downloading ephemeris database...
hjd_dict.pickle

Downloading ephemeris database failed. A download will be attempted next time.
Error: <class 'urllib.error.HTTPError'>
()
Traceback (most recent call last):
  File "make_lightcurve.py", line 11, in <module>
    import pylightcurve as plc
  File "/usr/local/lib/python3.7/site-packages/pylightcurve/__init__.py", line 11, in <module>
    from .catalogues_celestial_sphere import *
  File "/usr/local/lib/python3.7/site-packages/pylightcurve/catalogues_celestial_sphere.py", line 81, in <module>
    hjd_dict = open_dict(glob.glob(os.path.join(databases.ephemeris, 'hjd_dict.pickle''*'))[0])
IndexError: list index out of range

Any insights?

Thanks a bunch,

Julia

**Comment by jbrande** [comment]
Was this closed due to the problem being resolved somehow? If so, could you please share that solution? If not, could you reopen the issue?

**Comment by atsiaras** [comment]
Please upgrade to the latest version 3.0.4, the issue has been resolved.

**Comment by jbrande** [comment]
Thanks!
