### ISSUE TITLE
More precision for timing in results.txt file

### ISSUE THREAD

**Issue by elisabethadams** [ucl-exoplanets/pylightcurve#4]
The fit results file only outputs single-digit errors on the transit midtimes, which is leading to loss of precision when converting from days to seconds (0.0001 d is 8.6 sec), e.g.:

# variable	result	uncertainty
T_mid_0	2451234.5678	-0.0005 +0.0007

Relatedly: is there a way to get access to the fit results in their full precision directly? (ie, without having to read back in the output file)

**Comment by atsiaras** [comment]
Thanks for the note. I had implemented a fix for that but had not pushed it. If you get the new commit it should be fixed. Otherwise, this only way to access the results is through the .pickle file.
