### ISSUE TITLE
Results file does not print midtimes if multiple transits of the same epoch

### ISSUE THREAD

**Issue by elisabethadams** [ucl-exoplanets/pylightcurve#7]
I have 5 light curves that I am simultaneously fitting for a transiting planet system, two of which have the same epoch. However, I only get four T_mid values back in the fit file. I'm guessing they're getting tagged by epoch and only one value is reported... but which one? Please fix :)

Thanks!
Elisabeth

**Comment by atsiaras** [comment]
Hi Elisabeth,

observations obtained at the same epoch are modelled with the same Tmid, this is why  you have less parameters (one Tmid parameter per epoch, not per observation). There is no reason to have two parameters for light-curves observed during the same night. If you want to use different Tmid parameters you should model them independently. I don't see any reason for doing that unless you want to check if only of the two has aa timing bias (e.g. wrong computer time).

**Comment by elisabethadams** [comment]
Hi Angelos,

I want to use the common fit for all the other parameters (a/R, i, etc) but if I have two transits on the same night and one has much better photometry, and hence timing, than the other that would be good to know. But I see your point and may do it another way.

**Comment by atsiaras** [comment]
Hi Elisabeth,

if one light-curve is more precise then it is naturally weighted more so this is the one that will inform the final value of the common parameter. Check the residuals. If the two light-curves do not agree has, then residuals will be problematic for both. Alternatively, fit them independently, check for statistically significant differences, and if you don't find any then you can safely analyse them together.
